//
//    Copyright (C) 2026 Robert Ambrose N7GET
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "sdkconfig.h"

#include "ax25_config_defaults.h"

#define AX25_CFG_STRINGIFY_INNER(x) #x
#define AX25_CFG_STRINGIFY(x) AX25_CFG_STRINGIFY_INNER(x)

const ax25_cfg_param_t ax25_cfg_defaults_schema[] = {
    {
        .parameter = "ax25.router.max_ports",
        .nvs_key = "ax25_route_51fc",
        .default_value = AX25_CFG_STRINGIFY(CONFIG_AX25_ROUTER_MAX_PORTS),
        .range = "2 32",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "ax25.router.queue_depth",
        .nvs_key = "ax25_route_135f",
        .default_value = "8",
        .range = "2 32",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "digi.callsign",
        .nvs_key = "digi_callsign",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "beacon.destination",
        .nvs_key = "beac_dst_a4c2",
        .default_value = "BEACON",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "beacon.every",
        .nvs_key = "beac_ev_2f51",
        .default_value = "0",
        .range = "0 10080",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "beacon.source",
        .nvs_key = "beac_src_8d3",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "beacon.text",
        .nvs_key = "beac_txt_e7ac",
        .default_value = "ESP-AX25",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "beacon.via",
        .nvs_key = "beacon_via_316a",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "net.agwpe.port",
        .nvs_key = "net_agwpe_port",
        .default_value = "8000",
        .range = "1 65535",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.agwpe.max_clients",
        .nvs_key = "net_agw_m_f91a",
        .default_value = "4",
        .range = "1 32",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.agwpe.server.max_conns",
        .nvs_key = "net_agwpe__e4f7",
        .default_value = "1",
        .range = "1 32",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.agwpe.conn_task_stack",
        .nvs_key = "net_agw_c_stk",
        .default_value = "6144",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.accept_task_priority",
        .nvs_key = "net_kiss_ac_pri",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.accept_task_stack",
        .nvs_key = "net_kiss_ac_stk",
        .default_value = "4096",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.conn_task_priority",
        .nvs_key = "net_kiss_cn_pri",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.conn_task_stack",
        .nvs_key = "net_kiss_cn_stk",
        .default_value = "6144",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.max_conns",
        .nvs_key = "net_kiss_m_3fa8",
        .default_value = "4",
        .range = "1 16",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.tx_queue_depth",
        .nvs_key = "net_kiss_tx_qd",
        .default_value = "4",
        .range = "1 64",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.tx_task_priority",
        .nvs_key = "net_kiss_tx_pr",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.tx_task_stack",
        .nvs_key = "net_kiss_tx_st",
        .default_value = "3072",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.server_tx_queue_depth",
        .nvs_key = "net_kiss_sv_qd",
        .default_value = "4",
        .range = "1 64",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.server_tx_task_priority",
        .nvs_key = "net_kiss_sv_pr",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.server_tx_task_stack",
        .nvs_key = "net_kiss_sv_st",
        .default_value = "3072",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.kiss.port",
        .nvs_key = "net_kiss_port",
        .default_value = "8100",
        .range = "1 65535",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.log.conn_task_priority",
        .nvs_key = "net_log_cn_pri",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.log.conn_task_stack",
        .nvs_key = "net_log_cn_stk",
        .default_value = "3072",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.log.max_conns",
        .nvs_key = "net_log_ma_8db7",
        .default_value = "1",
        .range = "1 8",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.log.port",
        .nvs_key = "net_log_port",
        .default_value = "8300",
        .range = "1 65535",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.log.queue_depth",
        .nvs_key = "net_log_q_dep",
        .default_value = "32",
        .range = "1 1024",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.max_conns",
        .nvs_key = "net_moni_m_6f31",
        .default_value = "1",
        .range = "1 8",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.conn_task_priority",
        .nvs_key = "net_mon_cn_pri",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.conn_task_stack",
        .nvs_key = "net_mon_cn_stk",
        .default_value = "3072",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.tx_queue_depth",
        .nvs_key = "net_mon_tx_qd",
        .default_value = "4",
        .range = "1 64",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.tx_task_priority",
        .nvs_key = "net_mon_tx_pr",
        .default_value = "5",
        .range = "1 25",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.tx_task_stack",
        .nvs_key = "net_mon_tx_st",
        .default_value = "3072",
        .range = "1024 65536",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "net.monitor.port",
        .nvs_key = "net_monito_9631",
        .default_value = "8200",
        .range = "1 65535",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "uart.baud",
        .nvs_key = "uart_baud",
        .default_value = "9600",
        .range = "1200,2400,4800,9600,19200,38400,57600,115200",
        .type = AX25_CFG_TYPE_ENUM,
        .hide = false,
    },
    {
        .parameter = "uart.no",
        .nvs_key = "uart_no",
        .default_value = "1",
        .range = "0 2",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "uart.rx_pin",
        .nvs_key = "uart_rx_pin",
        .default_value = "7",
        .range = "0 48",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "uart.tx_pin",
        .nvs_key = "uart_tx_pin",
        .default_value = "6",
        .range = "0 48",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "wifi.ap.password",
        .nvs_key = "wifi_ap_pa_42b5",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = true,
    },
    {
        .parameter = "wifi.ap.ssid",
        .nvs_key = "wifi_ap_ssid",
        .default_value = "ESP-AX25-BBS",
        .range = "ESP-AX25",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "wifi.sta.password",
        .nvs_key = "wifi_sta_p_e677",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = true,
    },
    {
        .parameter = "wifi.sta.hostname",
        .nvs_key = "wifi_sta_host",
        .default_value = CONFIG_AX25_WIFI_STA_HOSTNAME_DEFAULT,
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
    {
        .parameter = "wifi.sta.connect_timeout_ms",
        .nvs_key = "wifi_sta_ct_ms",
        .default_value = "15000",
        .range = "0 600000",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "wifi.sta.max_waits",
        .nvs_key = "wifi_sta_m_wait",
        .default_value = "4",
        .range = "0 64",
        .type = AX25_CFG_TYPE_INT,
        .hide = false,
    },
    {
        .parameter = "wifi.sta.ssid",
        .nvs_key = "wifi_sta_ssid",
        .default_value = "",
        .range = "",
        .type = AX25_CFG_TYPE_STRING,
        .hide = false,
    },
};

const size_t ax25_cfg_defaults_schema_count =
    sizeof(ax25_cfg_defaults_schema) / sizeof(ax25_cfg_defaults_schema[0]);
